ALTER TABLE k8s_workloads
    DROP INDEX idx_k8s_workloads_owner,
    DROP COLUMN resource_created_at,
    DROP COLUMN revision,
    DROP COLUMN owner_uid,
    DROP COLUMN owner_name,
    DROP COLUMN owner_kind,
    DROP COLUMN is_terminal_failure,
    DROP COLUMN failed_replicas,
    DROP COLUMN active_replicas;
