CREATE TABLE IF NOT EXISTS log_backends (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL DEFAULT '',
    type VARCHAR(32) NOT NULL DEFAULT 'elasticsearch',
    status VARCHAR(24) NOT NULL DEFAULT 'unselected',
    generation BIGINT UNSIGNED NOT NULL DEFAULT 1,
    write_endpoints_json TEXT NOT NULL,
    query_endpoint VARCHAR(2048) NOT NULL DEFAULT '',
    dataset VARCHAR(100) NOT NULL DEFAULT 'ongrid.generic',
    namespace VARCHAR(100) NOT NULL DEFAULT 'default',
    index_pattern VARCHAR(255) NOT NULL DEFAULT 'logs-ongrid.*.otel-*',
    write_credential_ref VARCHAR(128) NOT NULL DEFAULT '',
    query_credential_ref VARCHAR(128) NOT NULL DEFAULT '',
    ca_pem TEXT NOT NULL,
    kibana_url VARCHAR(2048) NOT NULL DEFAULT '',
    tls_insecure BOOLEAN NOT NULL DEFAULT FALSE,
    detected_version VARCHAR(32) NOT NULL DEFAULT '',
    last_test_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at DATETIME(3) NULL,
    delete_marker BIGINT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_log_backend_name (name, generation, delete_marker),
    KEY idx_log_backends_status (status),
    KEY idx_log_backends_deleted_at (deleted_at)
);

CREATE TABLE IF NOT EXISTS log_backend_assignments (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    backend_id BIGINT UNSIGNED NOT NULL,
    edge_id BIGINT UNSIGNED NOT NULL,
    desired_generation BIGINT UNSIGNED NOT NULL DEFAULT 0,
    applied_generation BIGINT UNSIGNED NOT NULL DEFAULT 0,
    status VARCHAR(24) NOT NULL DEFAULT 'pending',
    probe_id VARCHAR(128) NOT NULL DEFAULT '',
    last_probe_at DATETIME(3) NULL,
    last_write_success_at DATETIME(3) NULL,
    last_error VARCHAR(1024) NOT NULL DEFAULT '',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at DATETIME(3) NULL,
    delete_marker BIGINT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_log_backend_edge (backend_id, edge_id, delete_marker),
    KEY idx_log_backend_assignments_backend (backend_id),
    KEY idx_log_backend_assignments_edge (edge_id),
    KEY idx_log_backend_assignments_status (status),
    KEY idx_log_backend_assignments_deleted_at (deleted_at)
);
