package callbacks

import (
	"context"
	"encoding/json"
	"regexp"
	"strings"
	"sync/atomic"

	einocallbacks "github.com/cloudwego/eino/callbacks"
	"github.com/cloudwego/eino/components"
	einomodel "github.com/cloudwego/eino/components/model"
	einotool "github.com/cloudwego/eino/components/tool"
	"github.com/cloudwego/eino/schema"
)

const draftConfigChangeToolName = "draft_config_change"

const AlertDraftGuardBlockedMessage = "这次没有通过 draft_config_change 生成可应用的 config_draft/draft_hash，我已拦截文字草案，避免把它误当成可确认的告警规则。继续这个创建需求时，我会生成正式草案并完成验证。"
const alertDraftGuardBlockedMessage = AlertDraftGuardBlockedMessage

var collectedSourceMentionRE = regexp.MustCompile(`\b(?:db|custom):[A-Za-z0-9_.:-]+`)

type AlertDraftGuardDeps struct {
	UserText string
}

// AlertDraftGuardHandler prevents a model-only "draft" from being
// persisted when the user is creating an alert rule. A real alert-rule
// draft must come from draft_config_change so the payload, preview, and
// draft_hash are generated by backend code rather than free-form text.
type AlertDraftGuardHandler struct {
	userText          string
	draftSucceeded    atomic.Bool
	hideSampleSources atomic.Bool
}

func NewAlertDraftGuardHandler(deps AlertDraftGuardDeps) *AlertDraftGuardHandler {
	if !looksLikeAlertRuleCreationRequest(deps.UserText) {
		return nil
	}
	return &AlertDraftGuardHandler{userText: deps.UserText}
}

func (h *AlertDraftGuardHandler) Needed(_ context.Context, info *einocallbacks.RunInfo, timing einocallbacks.CallbackTiming) bool {
	if h == nil || info == nil {
		return false
	}
	switch info.Component {
	case components.ComponentOfChatModel, components.ComponentOfTool:
		return timing == einocallbacks.TimingOnEnd
	default:
		return false
	}
}

func (h *AlertDraftGuardHandler) OnEnd(ctx context.Context, info *einocallbacks.RunInfo, output einocallbacks.CallbackOutput) context.Context {
	if h == nil || info == nil {
		return ctx
	}
	switch info.Component {
	case components.ComponentOfTool:
		tout := einotool.ConvCallbackOutput(output)
		if tout == nil {
			return ctx
		}
		switch info.Name {
		case draftConfigChangeToolName:
			if toolResultLooksLikeConfigDraft(tout.Response) {
				h.draftSucceeded.Store(true)
				if draftResultShouldHideSampleSources(tout.Response) {
					h.hideSampleSources.Store(true)
				}
			}
		}
	case components.ComponentOfChatModel:
		mo := einomodel.ConvCallbackOutput(output)
		if mo == nil || mo.Message == nil {
			return ctx
		}
		if messageCallsTool(mo.Message, draftConfigChangeToolName) {
			return ctx
		}
		mo.Message.Content = h.SanitizeAssistantContent(mo.Message.Content)
	}
	return ctx
}

func (h *AlertDraftGuardHandler) OnStart(ctx context.Context, _ *einocallbacks.RunInfo, _ einocallbacks.CallbackInput) context.Context {
	return ctx
}

func (h *AlertDraftGuardHandler) OnError(ctx context.Context, _ *einocallbacks.RunInfo, _ error) context.Context {
	return ctx
}

func (h *AlertDraftGuardHandler) OnStartWithStreamInput(ctx context.Context, _ *einocallbacks.RunInfo, _ *schema.StreamReader[einocallbacks.CallbackInput]) context.Context {
	return ctx
}

func (h *AlertDraftGuardHandler) OnEndWithStreamOutput(ctx context.Context, _ *einocallbacks.RunInfo, _ *schema.StreamReader[einocallbacks.CallbackOutput]) context.Context {
	return ctx
}

func (h *AlertDraftGuardHandler) SanitizeAssistantContent(content string) string {
	if h == nil {
		return content
	}
	if h.draftSucceeded.Load() {
		if h.hideSampleSources.Load() {
			return sanitizeCollectedSampleSourceMentions(content)
		}
		return content
	}
	if !looksLikeConfirmableAlertDraft(content) {
		return content
	}
	return alertDraftGuardBlockedMessage
}

func AlertDraftGuardFromHandlers(handlers []einocallbacks.Handler) *AlertDraftGuardHandler {
	for _, h := range handlers {
		if guard, ok := h.(*AlertDraftGuardHandler); ok {
			return guard
		}
	}
	return nil
}

func LooksLikeAlertRuleCreationText(text string) bool {
	return looksLikeAlertRuleCreationRequest(text)
}

func messageCallsTool(msg *schema.Message, toolName string) bool {
	if msg == nil {
		return false
	}
	for _, tc := range msg.ToolCalls {
		if strings.EqualFold(strings.TrimSpace(tc.Function.Name), toolName) {
			return true
		}
	}
	return false
}

func LooksLikeAlertDraftGuardBlockedMessage(content string) bool {
	lower := strings.ToLower(content)
	return strings.Contains(lower, "draft_config_change") &&
		strings.Contains(lower, "config_draft") &&
		(strings.Contains(content, "拦截文字草案") ||
			strings.Contains(content, "没有通过 draft_config_change") ||
			strings.Contains(content, "我还没有通过 draft_config_change"))
}

func looksLikeAlertRuleCreationRequest(text string) bool {
	lower := strings.ToLower(text)
	if !containsAnyNeedle(text, lower, []string{
		"创建", "新增", "添加", "配置", "生成",
		"create", "add", "configure", "new", "generate",
	}) {
		return false
	}
	return containsAnyNeedle(text, lower, []string{
		"告警", "告警规则", "监控规则", "规则", "链路", "日志",
		"alert", "rule", "monitoring rule", "slo", "burn rate", "metric", "log", "trace",
	})
}

func looksLikeConfirmableAlertDraft(content string) bool {
	lower := strings.ToLower(content)
	if containsAnyNeedle(content, lower, []string{
		"config_draft",
		"apply_config_change",
	}) {
		return true
	}
	hasAlertRule := strings.Contains(content, "告警") ||
		strings.Contains(content, "规则键") ||
		strings.Contains(content, "规则设计") ||
		strings.Contains(strings.ToLower(content), "规则 key") ||
		strings.Contains(lower, "alert") ||
		strings.Contains(lower, "rule_key") ||
		strings.Contains(lower, "draft_hash")
	if !hasAlertRule {
		return false
	}
	confirmableNeedles := []string{
		"草案哈希",
		"确认应用",
		"告警规则草案",
		"draft_hash",
		"sha256:",
		"config_draft",
		"apply_config_change",
	}
	for _, needle := range confirmableNeedles {
		if strings.Contains(lower, needle) || strings.Contains(content, needle) {
			return true
		}
	}
	hasRuleDesign := containsAnyNeedle(content, lower, []string{
		"规则设计",
		"规则 key",
		"规则key",
		"promql",
		"触发条件",
		"生效范围",
	})
	asksForConfirm := containsAnyNeedle(content, lower, []string{
		"需要确认",
		"确认创建",
		"要确认",
		"确认吗",
		"confirm",
		"approve",
	})
	if hasRuleDesign && asksForConfirm {
		return true
	}
	return false
}

func containsAnyNeedle(text, lowerText string, needles []string) bool {
	for _, needle := range needles {
		if strings.Contains(lowerText, needle) || strings.Contains(text, needle) {
			return true
		}
	}
	return false
}

func toolResultLooksLikeConfigDraft(result string) bool {
	var resp struct {
		Kind      string `json:"kind"`
		DraftHash string `json:"draft_hash"`
	}
	if err := json.Unmarshal([]byte(result), &resp); err == nil &&
		strings.TrimSpace(resp.Kind) == "config_draft" &&
		strings.TrimSpace(resp.DraftHash) != "" {
		return true
	}
	lower := strings.ToLower(result)
	return strings.Contains(lower, "config_draft") &&
		strings.Contains(lower, "draft_hash")
}

func draftResultShouldHideSampleSources(result string) bool {
	var resp struct {
		Payload struct {
			Rule struct {
				Kind string                 `json:"kind"`
				Spec map[string]interface{} `json:"spec"`
			} `json:"rule"`
		} `json:"payload"`
	}
	if err := json.Unmarshal([]byte(result), &resp); err != nil {
		return false
	}
	if strings.TrimSpace(resp.Payload.Rule.Kind) != "metric_raw" || resp.Payload.Rule.Spec == nil {
		return false
	}
	if boolish(resp.Payload.Rule.Spec["source_explicit"]) {
		return false
	}
	for _, key := range []string{"expr", "promql", "query", "selector", "label_selector"} {
		if containsExplicitSourceMatcher(resp.Payload.Rule.Spec[key]) {
			return false
		}
	}
	return true
}

func boolish(raw interface{}) bool {
	switch v := raw.(type) {
	case bool:
		return v
	case string:
		switch strings.ToLower(strings.TrimSpace(v)) {
		case "true", "yes", "y", "1", "explicit", "user", "specified", "requested":
			return true
		default:
			return false
		}
	default:
		return false
	}
}

func containsExplicitSourceMatcher(raw interface{}) bool {
	text, ok := raw.(string)
	if !ok {
		return false
	}
	return strings.Contains(text, `ongrid_source="`) ||
		strings.Contains(text, `device_id="`) ||
		strings.Contains(text, `instance="`) ||
		strings.Contains(text, `service="`)
}

func sanitizeCollectedSampleSourceMentions(content string) string {
	return collectedSourceMentionRE.ReplaceAllStringFunc(content, func(match string) string {
		if strings.HasPrefix(match, "custom:") {
			return "某个自定义采集源"
		}
		return "某个数据库采集源"
	})
}

var _ einocallbacks.Handler = (*AlertDraftGuardHandler)(nil)
var _ einocallbacks.TimingChecker = (*AlertDraftGuardHandler)(nil)
