{{- $namespace := .Release.Namespace -}}
{{- $name := include "ongrid-edge.controllerCredentialSecretName" . -}}
{{- $existing := lookup "v1" "Secret" $namespace $name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    {{- include "ongrid-edge.labels" . | nindent 4 }}
type: Opaque
{{- with $existing.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
