apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ongrid-edge.fullname" . }}-controller-bootstrap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ongrid-edge.labels" . | nindent 4 }}
type: Opaque
stringData:
  cluster-id: {{ required "enrollment.clusterID is required" .Values.enrollment.clusterID | quote }}
  bootstrap-token: {{ required "enrollment.controllerBootstrapToken is required" .Values.enrollment.controllerBootstrapToken | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ongrid-edge.fullname" . }}-node-bootstrap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ongrid-edge.labels" . | nindent 4 }}
type: Opaque
stringData:
  cluster-id: {{ required "enrollment.clusterID is required" .Values.enrollment.clusterID | quote }}
  bootstrap-token: {{ required "enrollment.nodeBootstrapToken is required" .Values.enrollment.nodeBootstrapToken | quote }}
