apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ongrid-edge.nodeServiceAccount" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ongrid-edge.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ongrid-edge.telemetryGatewayServiceAccount" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ongrid-edge.labels" . | nindent 4 }}
    app.kubernetes.io/component: telemetry-gateway
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ongrid-edge.metricsScraperServiceAccount" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ongrid-edge.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics-scraper
automountServiceAccountToken: {{ and (eq (include "ongrid-edge.kubernetesMetricsEnabled" .) "true") (eq (include "ongrid-edge.kubernetesMetricsMode" .) "scraper") (eq (include "ongrid-edge.kubernetesAppMetricsDiscoveryEnabled" .) "true") }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ongrid-edge.controllerServiceAccount" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ongrid-edge.labels" . | nindent 4 }}
