package basetool

import "context"

// artifact_source.go — ctx propagation for "where did this artifact come from".
// serve_page (and any future artifact-producing tool) reads it so the
// operations UI can show a 生成来源 / source column: was this page generated by
// the chat assistant, or by a workflow run? The chat runtime stamps "chat",
// the flow tool-invoker stamps "workflow"; absent = unknown.
//
// Same leaf-package rationale as session.go / bound_credentials.go: both the
// producers (chatruntime, cmd/main flowToolInvoker) and the consumer
// (tools/serve_page via the PageStore in cmd/main) depend on basetool without
// an import cycle.

type artifactSourceCtxKeyT struct{}

var artifactSourceCtxKey = artifactSourceCtxKeyT{}

// Well-known source codes (stored verbatim; the SPA localizes them).
const (
	ArtifactSourceChat     = "chat"
	ArtifactSourceWorkflow = "workflow"
)

// WithArtifactSource returns ctx tagged with the artifact's origin. Empty =
// no-op so callers can pass through an unknown source harmlessly.
func WithArtifactSource(ctx context.Context, src string) context.Context {
	if src == "" {
		return ctx
	}
	return context.WithValue(ctx, artifactSourceCtxKey, src)
}

// ArtifactSourceFromContext returns the origin code, or "" when none was
// attached.
func ArtifactSourceFromContext(ctx context.Context) string {
	v, _ := ctx.Value(artifactSourceCtxKey).(string)
	return v
}
